drop database if exists employee;
create database employee;
use employee;
create table DEPARTMENTS(DEPARTMENT_ID INT,
DEPARTMENT_NAME VARCHAR(100));
CREATE TABLE LOCATION(LOCATION_ID INT,
LOCATION VARCHAR(30));
CREATE TABLE EMPLOYEES(EMPLOYEE_ID INT,
EMPLOYEE_NAME VARCHAR(50),
GENDER ENUM ('M','F'),
AGE INT,
HIRE_DATE DATE,
DESIGNATION VARCHAR(100),
DEPARTMENT_ID INT,
LOCATION_ID INT,
SALARY DECIMAL(10,2))
;
SELECT * FROM DEPARTMENTS;
SELECT * FROM LOCATION;
SELECT * FROM EMPLOYEES;
ALTER TABLE EMPLOYEES
ADD EMAIL VARCHAR(100);
ALTER TABLE EMPLOYEES
MODIFY DESIGNATION TEXT(100);
ALTER TABLE EMPLOYEES
DROP AGE;
ALTER TABLE EMPLOYEES
RENAME COLUMN HIRE_DATE TO DATE_OF_JOINING;
RENAME TABLE DEPARTMENTS TO DEPARTMENTS_INFO;
RENAME TABLE LOCATION TO LOCATIONS;
TRUNCATE TABLE EMPLOYEES;
DROP TABLE EMPLOYEES;
DROP DATABASE EMPLOYEE;
create database employee;
use employee;
CREATE table DEPARTMENTS (DEPARTMENT_ID INT PRIMARY KEY,
DEPARTMENT_NAME VARCHAR(100) NOT NULL UNIQUE);
CREATE TABLE LOCATION(LOCATION_ID INT PRIMARY KEY AUTO_INCREMENT,
LOCATION VARCHAR(30) NOT NULL UNIQUE);
CREATE TABLE EMPLOYEES(EMPLOYEE_ID INT PRIMARY KEY,
EMPLOYEE_NAME VARCHAR(50) NOT NULL,
GENDER CHAR(1) CHECK(GENDER IN ('M','F')) ,
AGE INT CHECK (AGE>=18),
HIRE_DATE DATE DEFAULT (CURRENT_DATE),
DESIGNATION TEXT (100),
DEPARTMENT_ID INT,
LOCATION_ID INT,
SALARY DECIMAL(10,2),
EMAIL VARCHAR(100),
FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID),
FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(LOCATION_ID));

















